apiVersion: v1
kind: PersistentVolume
metadata:
  name: monitoring-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /data-1/monitoring
    server: 192.168.164.206
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage