apiVersion: v1
kind: ConfigMap
metadata:
  name: web-backend-application-properties-configmap
  namespace: bigdata
data:
  application.properties: |
    spring.application.name=web-backend
    spring.data.redis.host=redis-sentinel-node-0.redis-sentinel-headless.bigdata.svc.cluster.local
    spring.data.redis.port=6379

    spring.data.rest.base-path=/api
    allowed.origins=http://quanda.web-frontend.local

    server.servlet.context-path=/
    spring.websocket.allowed-origins=${allowed.origins}