apiVersion: v1
kind: ConfigMap
metadata:
  name: web-backend-application-properties-configmap
  namespace: bigdata
data:
  application.properties: |
    spring.application.name=web-backend

    spring.redis.sentinel.master=mymaster
    spring.redis.sentinel.nodes=redis-sentinel-node-0.redis-sentinel-headless.bigdata.svc.cluster.local:26379,redis-sentinel-node-1.redis-sentinel-headless.bigdata.svc.cluster.local:26379,redis-sentinel-node-2.redis-sentinel-headless.bigdata.svc.cluster.local:26379
    spring.redis.password=quanda

    spring.data.rest.base-path=/api
    allowed.origins=http://quanda.web-frontend.local

    server.servlet.context-path=/
    spring.websocket.allowed-origins=${allowed.origins}