apiVersion: v1
kind: ConfigMap
metadata:
  name: web-backend-application-properties-configmap
  namespace: bigdata
data:
  application.properties: |
    spring.application.name=web-backend
    spring.redis.host=redis-master.bigdata.svc.cluster.local
    spring.redis.port=6379
    spring.redis.password=quanda
    
    spring.data.rest.base-path=/api
    allowed.origins=http://quanda.web-frontend.local

    server.servlet.context-path=/
    spring.websocket.allowed-origins=${allowed.origins

    spring.datasource.url=jdbc:postgresql://postgresql-db.bigdata.svc.cluster.local:5432/taxi_trip_db
    spring.datasource.username=quanda
    spring.datasource.password=quanda
    spring.datasource.driver-class-name=org.postgresql.Driver

    spring.jpa.hibernate.ddl-auto=none
    spring.jpa.show-sql=false
    spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
    spring.jpa.properties.hibernate.format_sql=true