architecture: standalone

image:
  registry: docker.io
  repository: bitnami/redis
  tag: 8.0.2-debian-12-r3

auth:
  enabled: true
  password: "quanda"

master:
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi