architecture: replication

auth:
  enabled: true
  password: "quanda"

master:
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

replica:
  replicaCount: 3
  persistence:
    enabled: true
    existingClaim: redis-pvc
    size: 3Gi

sentinel:
  enabled: true
  replicas: 3