apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: bigdata
spec:
  serviceName: kafka
  replicas: 3
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - name: kafka
          image: bitnami/kafka:3.6
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_CFG_ZOOKEEPER_CONNECT
              value: zookeeper.bigdata.svc.cluster.local:2181

            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: PLAINTEXT:PLAINTEXT

            - name: KAFKA_CFG_LISTENERS
              value: PLAINTEXT://:9092

            - name: KAFKA_CFG_ADVERTISED_LISTENERS_COMMAND
              value: "echo PLAINTEXT://$(hostname).kafka.bigdata.svc.cluster.local:9092"

            - name: KAFKA_BROKER_ID_COMMAND
              value: "echo ${HOSTNAME##*-}"

            - name: ALLOW_PLAINTEXT_LISTENER
              value: "yes"
              
          volumeMounts:
            - name: data
              mountPath: /bitnami/kafka
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: nfs-kafka-storage
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: bigdata
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - port: 9092
