global:
  storageClass: nfs-superset-storage

image:
  registry: docker.io
  repository: bitnami/superset
  tag: 4.1.2-debian-12-r6

auth:
  username: quanda
  password: quanda

ingress:
  enabled: true
  ingressClassName: nginx
  path: /
  hostname: quanda.superset.local

web:
  service:
    type: ClusterIP

postgresql:
  enabled: true
  auth:
    username: bn_superset
    password: superset
    database: bitnami_superset

redis:
  enabled: true
  architecture: standalone
  auth:
    enabled: true
    password: superset

externalDatabase:
  enabled: false

externalRedis:
  enabled: false

defaultInitContainers:
  waitForDB:
    enabled: false
  waitForRedis:
    enabled: false