apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-db-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /B/postgresql/
    server: 192.168.164.206
  persistentVolumeReclaimPolicy: Delete
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db-pvc
  namespace: bigdata
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-storage