storageClass: nfs-storage

ingress:
  enabled: true
  hostname: quanda.spark-ui.local
  ingressClassName: nginx
  path: /

metrics:
  enabled: true

master:
  resources:
    requests:
      cpu: 1000m
      memory: 1Gi
    limits:
      cpu: 2000m
      memory: 2Gi

worker:
  replicaCount: 2
  resources:
    requests:
      cpu: 2000m
      memory: 4Gi
    limits:
      cpu: 3000m
      memory: 6Gi