apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-ingestion
  namespace: nyc-taxi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-ingestion
  template:
    metadata:
      labels:
        app: data-ingestion
    spec:
      containers:
        - name: producer
          image: quandao073/nyc-taxi-trips-ingestion:v2.0
          command: ["/bin/sh"]
          args: ["-c", "tail -f /dev/null"]
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka.nyc-taxi.svc.cluster.local:9092
            - name: API_HOST
              value: http://api-server.nyc-taxi.svc.cluster.local:5000
            - name: SPEED
              value: "2.0"
      restartPolicy: Always
