apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-source-pv
spec:
  capacity:
    storage: 30Gi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 192.168.164.206
    path: /A/data_source
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-source-pvc
  namespace: bigdata
spec:
  storageClassName: nfs-storage
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 30Gi
