executor: "LocalExecutor"

envFrom:
  - configMapRef:
      name: airflow-env-vars

images:
  airflow:
    repository: quandao073/airflow
    tag: v1.0
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  web:
    enabled: true
    path: /
    host: quanda.airflow-web.local
    ingressClassName: nginx

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: quanda
    password: quanda
  service:
    type: ClusterIP
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

scheduler:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

triggerer:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

dags:
  persistence:
    enabled: true
    storageClassName: nfs-airflow-storage

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: "quanda"
    password: "quanda"

redis:
  enabled: false
