executor: "LocalExecutor"

# envFrom:
#   - configMapRef:
#       name: airflow-env-vars

env:
  - name: DATA_INGESTION__TAXI_TYPE
    value: "yellow"
  - name: DATA_INGESTION__API_HOST
    value: "http://data-ingestion-api-server.bigdata.svc.cluster.local:5000"
  - name: DATA_INGESTION__SPEED
    value: "2.0"
  - name: DATA_INGESTION__QUERY_PAGE_SIZE
    value: "20"
  - name: KAFKA__BOOTSTRAP_SERVERS
    value: "kafka.bigdata.svc.cluster.local:9092"
  - name: SPARK_STREAMING__TRIGGER_TIME
    value: "5 minutes"
  - name: HDFS__URI
    value: "hdfs://hadoop-hadoop-hdfs-nn:9000"
  - name: REDIS__SENTINEL_HOST
    value: "redis-sentinel.bigdata.svc.cluster.local"
  - name: REDIS__SENTINEL_PORT
    value: "26379"
  - name: REDIS__MASTER_NAME
    value: "mymaster"
  - name: REDIS__PASSWORD
    value: "quanda"


images:
  airflow:
    repository: quandao073/airflow
    tag: v1.1
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  web:
    enabled: true
    path: /
    host: quanda.airflow-web.local
    ingressClassName: nginx

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: quanda
    password: quanda
  service:
    type: ClusterIP
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

scheduler:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

triggerer:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc

logs:
  persistence:
    enabled: true
    size: 20Gi
    existingClaim: airflow-logs-pvc

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: "quanda"
    password: "quanda"

redis:
  enabled: false
