executor: "LocalExecutor"

env:
  - name: DATA_INGESTION__TAXI_TYPE
    value: "yellow"
  - name: DATA_INGESTION__API_HOST
    value: "http://data-ingestion-api-server.bigdata.svc.cluster.local:5000"
  - name: DATA_INGESTION__SPEED
    value: "1.5"
  - name: DATA_INGESTION__QUERY_PAGE_SIZE
    value: "20"
  - name: KAFKA__BOOTSTRAP_SERVERS
    value: "kafka.bigdata.svc.cluster.local:9092"
  - name: SPARK_STREAMING__TRIGGER_TIME
    value: "3 minutes"
  - name: HDFS__URI
    value: "hdfs://hadoop-hadoop-hdfs-nn:9000"
  - name: REDIS__HOST
    value: "redis-master.bigdata.svc.cluster.local"
  - name: REDIS__PORT
    value: "6379"
  - name: REDIS__PASSWORD
    value: "quanda"
  - name: POSTGRES__URI
    value: "jdbc:postgresql://postgresql-db.bigdata.svc.cluster.local:5432"
  - name: POSTGRES__USERNAME
    value: "quanda"
  - name: POSTGRES__PASSWORD
    value: "quanda"
  - name: POSTGRES__DATABASE
    value: "taxi_trip_db"

images:
  airflow:
    repository: quandao073/airflow
    tag: v1.1
    pullPolicy: IfNotPresent

ingress:
  enabled: true
  web:
    enabled: true
    path: /
    host: quanda.airflow-web.local
    ingressClassName: nginx

webserver:
  defaultUser:
    enabled: true
    role: Admin
    username: quanda
    password: quanda
  service:
    type: ClusterIP
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
    - name: airflow-data-source
      mountPath: /tmp/data
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc
    - name: airflow-data-source
      persistentVolumeClaim:
        claimName: airflow-datasource-pvc

scheduler:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
    - name: airflow-data-source
      mountPath: /tmp/data
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc
    - name: airflow-data-source
      persistentVolumeClaim:
        claimName: airflow-datasource-pvc

triggerer:
  extraVolumeMounts:
    - name: airflow-code
      mountPath: /opt/airflow/code
    - name: airflow-data-source
      mountPath: /tmp/data
  extraVolumes:
    - name: airflow-code
      persistentVolumeClaim:
        claimName: airflow-code-pvc
    - name: airflow-data-source
      persistentVolumeClaim:
        claimName: airflow-datasource-pvc

dags:
  persistence:
    enabled: true
    existingClaim: airflow-dags-pvc

logs:
  persistence:
    enabled: true
    size: 5Gi
    existingClaim: airflow-logs-pvc

postgresql:
  enabled: true
  auth:
    enablePostgresUser: true
    postgresPassword: postgres
    username: "quanda"
    password: "quanda"

redis:
  enabled: false
