apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: data-collector
  name: data-collector-deployment
  namespace: air-quality
spec:
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: data-collector
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: data-collector
      namespace: air-quality
    spec:
      containers:
        - image: quandao073/air-quality-data-collector:latest
          imagePullPolicy: Always
          name: data-collector
          ports:
            - containerPort: 8081
              name: tcp
              protocol: TCP