apiVersion: v1
kind: Service
metadata:
  name: data-collector-service
  namespace: air-quality
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: tcp
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: data-collector
  sessionAffinity: None
  type: ClusterIP